name: PIPELINE1

on:
  push:
    branches:
      - main


jobs:
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production

    steps:

      - name: Baixar artefato
        uses: actions/download-artifact@v4
        with:
          name: codigo-buildado
      
      - name: Extrair artefato
        run: unzip pipeline-demo.zip

      - name: Simular deploy
        run: echo "Deploy feito com sucesso em produção"