name: PIPELINE1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubunto-latest
    steps:
      - name: Checkout do código
      - uses: actions/checkout@v3

      - name: Configurar o python
      - uses: actions/setup-python@v5
      - with:
          python-version: '3.11'

      - name: Intalar as dependencias
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Teste
      - run: |
          pytest
