name: Pipeline dev

on:
  push:
    branches:
      - main
      

jobs:

  security:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Cache de dependencias Python
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Instalar o dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2


  quality:
    runs-on: ubuntu-latest
    needs: security

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Cache de dependencias Python
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Instalar o dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      

      - name: Análise com SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=pedro-albertini_app-palmeiras
            -Dsonar.organization=pedro-albertini  
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Rodar lint
        run: python -m pylint --fail-under=7.0 --disable=C0114,C0116 test_app.py

      - name: Rodar corevage
        run: |
          python -m coverage run -m pytest test_app.py
          python -m coverage report --fail-under=80

  build:
    runs-on: ubuntu-latest
    needs: quality

    steps:
    
      # - name: Checkout do código
      #   uses: actions/checkout@v3

      # - name: Configurar o python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'

      # - name: Cache de dependencias Python
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-

      # - name: Intalar as dependencias
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build e Push da Imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: alberttini3/pipeline-ci:latest

  test:

    needs: build
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #    python-version: [ '3.9', '3.10', '3.11', '3.12' ]
    #    os: [ubuntu-latest, windows-latest, macos-latest]
      
    # runs-on: ${{ matrix.os }}

    # steps:
    #   - name: Checkout do código
    #     uses: actions/checkout@v3

    #   - name: Configurar o python
    #     uses: actions/setup-python@v5
    #     with:
    #       python-version: ${{ matrix.python-version }}

    #   - name: Cache de dependencias Python
    #     uses: actions/cache@v4
    #     with:
    #       path: ~/.cache/pip
    #       key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    #       restore-keys: |
    #         ${{ runner.os }}-pip-

    #   - name: Intalar as dependencias
    #     run: |
    #       python -m pip install --upgrade pip
    #       pip install -r requirements.txt

    #   - name: Teste
    #     run: pytest

    steps:
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Rodar testes dentro do Container
        run: docker run alberttini3/pipeline-ci:latest pytest

    